name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install CocoaPods
      run: pod install --project-directory=./Example/
    - name: Build
      run: xcodebuild -workspace "./Example/FoursquareAPIClient.xcworkspace" -scheme FoursquareAPIClient -sdk iphonesimulator -configuration Debug build -destination 'platform=iOS Simulator,OS=12.4,name=iPhone 6' clean test 
