name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Change directory
      run: cd Example
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install CocoaPods
      run: pod install
    - name: Build
      run: xcodebuild -workspace "FoursquareAPIClient.xcworkspace" -scheme FoursquareAPIClient -sdk iphonesimulator -configuration Debug build 
